[package]
name = "firebase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
fireauth = "0.1.5"
tokio = { version = "1.19.2", features = ["macros", "sync", "rt-multi-thread"] }
